Update shell tools and scripting

diff --git a/shell tools and scripting b/shell tools and scripting
--- a/shell tools and scripting
+++ b/shell tools and scripting
@@ -43,3 +43,31 @@ polo () {
  echo "Everything went according to plan"
 
 3)
+#!/usr/bin/env bash
+
+counter=0
+
+while true; do
+    ((counter++))
+    /home/mahmoud/source/rare.sh > /home/mahmoud/stdout.txt 2> /home/mahmoud/stderr.txt
+
+    if [[ $? -ne 0 ]]; then
+        cat /home/mahmoud/stdout.txt
+        cat /home/mahmoud/stderr.txt
+        echo "the script failed after $counter runs"
+        break
+    fi
+done    
+
+4. As we covered in the lecture find’s -exec can be very powerful for performing operations over the files we are searching for. However, what if we want to do something with all the files, like creating a zip file? As you have seen so far commands will take input from both arguments and STDIN. When piping commands, we are connecting STDOUT to STDIN, but some commands like tar take inputs from arguments. To bridge this disconnect there’s the xargs command which will execute a command using STDIN as arguments. For example ls | xargs rm will delete the files in the current directory.
+
+Your task is to write a command that recursively finds all HTML files in the folder and makes a zip with them. Note that your command should work even if the files have spaces (hint: check -d flag for xargs).
+
+If you’re on macOS, note that the default BSD find is different from the one included in GNU coreutils. You can use -print0 on find and the -0 flag on xargs. As a macOS user, you should be aware that command-line utilities shipped with macOS may differ from the GNU counterparts; you can install the GNU versions if you like by using brew.
+
+4)
+find . -name '*.html' -type f | xargs -d '\n' zip all.zip
+
+5.(Advanced) Write a command or script to recursively find the most recently modified file in a directory. More generally, can you list all files by recency?
+
+5)
